// BGSD
include <../lib/boardgame_insert_toolkit_lib.4.scad>;
data = [
    // Source STL: Tiles.stl
    // STL bbox min [-191, -62.5, 0] max [-113, 101, 69] size [78, 163.5, 69]
    // Detected compartments: 2; wall thickness: 1.5mm
    [ OBJECT_BOX,
        [ NAME, "Tiles" ],
        [ BOX_SIZE_XYZ, [78, 163.5, 69] ],
        [ BOX_WALL_THICKNESS, 1.5 ],
        [ BOX_LID,
            [ NAME, "lid" ],
            [ LID_TYPE, LID_CAP ],
            [ LABEL,
                [ NAME, "lid label" ],
                [ LBL_TEXT, "Tiles" ],
                [ LBL_PLACEMENT, CENTER ],
                [ LBL_SIZE, AUTO ],
                [ LBL_DEPTH, 0.2 ],
            ],
        ],
        [ LABEL,
            [ NAME, "Tiles label" ],
            [ LBL_TEXT, "Tiles" ],
            [ LBL_PLACEMENT, CENTER ],
            [ LBL_SIZE, AUTO ],
            [ LBL_DEPTH, 0.2 ],
        ],
        [ BOX_FEATURE,
            [ NAME, "Tiles cavity 1" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [75, 84, 67.5] ],
            [ FTR_NUM_COMPARTMENTS_XY, [1, 1] ],
            [ FTR_SHAPE, SQUARE ],
            [ POSITION_XY, [0, 0] ],
            [ FTR_CUTOUT_SIDES_4B, [false, false, true, false] ],
            [ FTR_CUTOUT_TYPE, BOTH ],
            [ FTR_CUTOUT_HEIGHT_PCT, 100 ],
            [ FTR_CUTOUT_DEPTH_PCT, 25 ],
            [ FTR_CUTOUT_WIDTH_PCT, 50 ],
            [ LABEL,
                [ NAME, "Tiles cavity 1 label" ],
                [ LBL_TEXT, "Tiles 1" ],
                [ LBL_PLACEMENT, CENTER ],
                [ LBL_SIZE, AUTO ],
                [ LBL_DEPTH, 0.2 ],
            ],
        ],
        [ BOX_FEATURE,
            [ NAME, "Tiles cavity 2" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [75, 75, 67.5] ],
            [ FTR_NUM_COMPARTMENTS_XY, [1, 1] ],
            [ FTR_SHAPE, SQUARE ],
            [ POSITION_XY, [0, 85.5] ],
            [ FTR_CUTOUT_SIDES_4B, [false, false, false, true] ],
            [ FTR_CUTOUT_TYPE, BOTH ],
            [ FTR_CUTOUT_HEIGHT_PCT, 100 ],
            [ FTR_CUTOUT_DEPTH_PCT, 25 ],
            [ FTR_CUTOUT_WIDTH_PCT, 50 ],
            [ LABEL,
                [ NAME, "Tiles cavity 2 label" ],
                [ LBL_TEXT, "Tiles 2" ],
                [ LBL_PLACEMENT, CENTER ],
                [ LBL_SIZE, AUTO ],
                [ LBL_DEPTH, 0.2 ],
            ],
        ],
    ],
];
Make(data);
